default:
	@echo "\n****Compilando o cliente****\n"
	(cd servidor; $(MAKE) )
	@echo "\n****Compilando o servidor****\n"
	(cd cliente; $(MAKE) )
clean:
	@echo "\n****Limpando os diretórios****\n"
	(cd servidor; $(MAKE) clean)
	(cd cliente; $(MAKE) clean)

